version: '3.8'

services:
  server:
    image: verbose-doodle
    deploy:
      replicas: 1
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        min-size: "10"
    ports:
      - "8080:8080"
    command: --addr :8080